### PR TITLE
Add DOCX image

### PR DESCRIPTION
**Pull request by WadeShuler**
DOCX is the standard MS Word document as of 2007.

### CODE REVIEW

**Comment by espaan** [comment]
I have some more icons coming from the reported issues and PRs, need to find a bit of time to get all those in.

**Comment by espaan** [comment]
I see that the icons are really huge in filesize. I will have to optimize them later on. For instance the 512px icon is typical 20kB vs 1MB of you docx.

**Comment by WadeShuler** [comment]
Thanks for the merge. Sorry, I used the original 512 DOC image as a base point, photo-shopped the text out, and added DOCX. Then generated the different sizes. I didn't pay any attention to file-size. I am on another computer and not at home, so I will get back to it when I can. I will fix the file size(s) and update.

**Comment by espaan** [comment]
Hi,
I think I will try with a trial version of Adobe Illustrator to get all icons updated with all the suggestions mentioned in the other tickets (other document types). I use iDraw on mac and the exported colors are not the same as the original icons. They are all vector based and then exported to png.

**Comment by WadeShuler** [comment]
I use the latest PhotoShop. You can save web versions, I just don't and leave it full res, and then save the web versions later when and where I need to. I don't think there is anything wrong with a 100-200kb image if it needs to be large. I agree 1mb is too big, and I didn't notice the 512 was that big. However a 512x512 image at 20kb may not look very good. I don't want to be able to notice that the images are compressed, but I don't want 1mb images either lol. - I will take some time out in a bit and double check the images vs sizes and re-submit them in a bit.

**Pull request merged**
